### ISSUE TITLE
About the `avirandor/jbb-chameleon7b`

### ISSUE THREAD

**Issue by LetheSec** [facebookresearch/multimodal-fusion-jailbreaks#2]
Hi, thank you for the nice work.

When I run the `run_attack.py` file, the following error occurs:
`datasets.exceptions.DatasetNotFoundError: Dataset 'javirandor/jbb-chameleon7b' doesn't exist on the Hub or cannot be accessed.`

Could you tell me how to get `avirandor/jbb-chameleon7b`? I didn't find it on HuggingFace.

https://github.com/facebookresearch/multimodal-fusion-jailbreaks/blob/cc1e0b3d9490a626ed6ae509477a75cd6bf86ff0/src/fusion_jailbreaks/utils.py#L43

**Comment by javirandor** [comment]
Thanks for spotting this. This is a typo and loading jailbreakbench directly should work. I will update the code ase asap.

https://huggingface.co/datasets/JailbreakBench/JBB-Behaviors/viewer

**Comment by LetheSec** [comment]
Thanks!
